In [1]:
import numpy as np

# Define two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Compute the tensor product
tensor_product = np.tensordot(A, B, axes=0)

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nTensor Product of A and B:")
print(tensor_product)


Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Tensor Product of A and B:
[[[[ 5  6]
   [ 7  8]]

  [[10 12]
   [14 16]]]


 [[[15 18]
   [21 24]]

  [[20 24]
   [28 32]]]]


In [4]:
import numpy as np

# Define the coefficients as complex numbers for qubit A and qubit B
a1 = complex(0.8, 0.2)  # coefficient for |0> state of qubit A
a2 = complex(0.6, -0.4)  # coefficient for |1> state of qubit A
b1 = complex(0.9, 0.3)  # coefficient for |0> state of qubit B
b2 = complex(0.3, 0.1)  # coefficient for |1> state of qubit B

# Define the states of qubit A and qubit B as column vectors
psi = np.array([[a1], [a2]])  # State of qubit A
phi = np.array([[b1], [b2]])  # State of qubit B

# Compute the tensor product of the states
tensor_product = np.kron(psi, phi)

# Print the result
print("Tensor product of |psi> and |phi> is:")
print(tensor_product)


Tensor product of |psi> and |phi> is:
[[0.66+0.42j]
 [0.22+0.14j]
 [0.66-0.18j]
 [0.22-0.06j]]


In [8]:
from qiskit import QuantumCircuit
from qiskit.quantum_info import Statevector
from qiskit.visualization import plot_bloch_multivector
from qiskit_aer import AerSimulator


# Create a Quantum Circuit
qc = QuantumCircuit(2)

# Apply Hadamard gate on qubit 0
qc.h(0)

# Apply X gate on qubit 1
qc.x(1)

simulator = AerSimulator()
# Simulate the circuit
job = simulator.run(qc, shots=100)

# Get the result
result = job.result()

# Visualize the circuit
print(qc)

state = Statevector(qc)
print(state)



     ┌───┐
q_0: ┤ H ├
     ├───┤
q_1: ┤ X ├
     └───┘
Statevector([0.        +0.j, 0.        +0.j, 0.70710678+0.j,
             0.70710678+0.j],
            dims=(2, 2))


In [3]:
import numpy as np

# Define quantum states
q0_state = np.array([1, 0])  # |0⟩
q1_state = np.array([0, 1])  # |1⟩

# Apply Hadamard gate on qubit 0
H_gate = np.array([[1/np.sqrt(2), 1/np.sqrt(2)],
                   [1/np.sqrt(2), -1/np.sqrt(2)]])
q0_after_H = np.dot(H_gate, q0_state)

# Apply X gate on qubit 1
X_gate = np.array([[0, 1],
                   [1, 0]])
q1_after_X = np.dot(X_gate, q1_state)

# Compute the tensor product of the quantum states after the operations
final_state = np.kron(q0_after_H, q1_after_X)

print("Final Quantum State:")
print(final_state)


Final Quantum State:
[0.70710678 0.         0.70710678 0.        ]
