In [3]:
 # The function is defined as:
    # f(00) = f(11) = 00
    # f(01) = f(10) = 11
∣x,y⟩→∣x,y⊕f(x)⟩ 
∣00,00⟩→∣00,00⟩
∣00,01⟩→∣00,01⟩
∣00,10⟩→∣00,10⟩
∣00,11⟩→∣00,11⟩,
∣01,00⟩→∣01,11⟩
∣01,01⟩→∣01,10⟩
∣01,10⟩→∣01,01⟩
∣01,11⟩→∣01,00⟩
∣10,00⟩→∣10,11⟩
∣10,01⟩→∣10,10⟩
∣10,10⟩→∣10,01⟩
∣10,11⟩→∣10,00⟩
∣11,00⟩→∣11,00⟩
∣11,01⟩→∣11,01⟩
∣11,10⟩→∣11,10⟩
∣11,11⟩→∣11,11⟩

SyntaxError: invalid character '∣' (U+2223) (3283338010.py, line 4)

In [4]:
import numpy as np

# Directly initialize the 16x16 transformation matrix
T = np.array([
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
])

# Print the transformation matrix
print(T)

[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]]


In [5]:
import cirq
import numpy as np
from collections import Counter

# Define the 8x8 unitary matrix for the oracle function
oracle_matrix = np.array([
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
])



# Create the oracle gate from the unitary matrix
oracle_gate = cirq.MatrixGate(oracle_matrix)

# Define the quantum circuit
def simon_circuit(oracle_gate):
    # Define four qubits
    qubits = cirq.LineQubit.range(4)
    
    # Create a quantum circuit
    circuit = cirq.Circuit()

    # Apply Hadamard gate to the first two qubits
    circuit.append([cirq.H(qubits[i]) for i in range(2)])

    # Apply the oracle gate
    circuit.append(oracle_gate(*qubits))

    # Apply Hadamard gate to the first two qubits
    circuit.append([cirq.H(qubits[i]) for i in range(2)])

    # Measure the first two qubits
    circuit.append([cirq.measure(qubits[i], key=f'result_{i}') for i in range(2)])

    return circuit

# Create the quantum circuit with the oracle gate
circuit = simon_circuit(oracle_gate)
# Simulate the circuit 100 times
simulator = cirq.Simulator()
result = simulator.run(circuit, repetitions=100)

# Collect the measurement results
measurements = result.measurements
counts = Counter(tuple(measurements[f'result_{i}'][j][0] for i in range(2)) for j in range(100))

# Print the measurement results
print("Measurement results (bitstring: frequency):")
for outcome, frequency in counts.items():
    print(f"{outcome}: {frequency}")

# Print the circuit
print("\nCircuit:")
print(circuit)

Measurement results (bitstring: frequency):
(np.int8(1), np.int8(1)): 46
(np.int8(0), np.int8(0)): 54

Circuit:
          ┌                               ┐
          │1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0│
          │0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0│
          │0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0│
          │0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0│
          │0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0│
          │0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0│
          │0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0│
0: ───H───│0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0│───H───M('result_0')───
          │0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0│
          │0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0│
          │0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0│
          │0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0│
          │0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0│
          │0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0│
          │0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0│
          │0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1│
          └                               ┘
          │
1: ───H───#2──────────────────────────────────H───M('result_1

In [6]:
# Example Simon's function with c = 011
# We'll map 3-bit strings to 2-bit outputs

def f(x: str) -> str:
    # Ensure x is 3-bit string like "000"
    pairs = {
        "000": "00", "011": "00",  # same output for this pair
        "001": "01", "010": "01",
        "100": "10", "111": "10",
        "101": "11", "110": "11",
    }
    return pairs[x]

# Test all inputs
for x in ["000","001","010","011","100","101","110","111"]:
    print(x, "->", f(x))


000 -> 00
001 -> 01
010 -> 01
011 -> 00
100 -> 10
101 -> 11
110 -> 11
111 -> 10


In [ ]:
Given that ( c ) is a two-bit binary number, we need to find ( c ) such that its inner product
with ( 00 ) and ( 11 ) is zero. 

Let's denote ( c ) as ( c = c1c0 ). 

The inner product of two binary numbers ( a ) and ( b ) is defined as: 

[ a . b = a0 . b0 + a1 . b1 ] 


Given the binary numbers: 

1. ( 00 ) 

2. ( 11 ) 

  
We need ( c ) such that: 


[ c . 00 = 0 ] 

[ c . 11 = 0 ] 

  

Let's calculate the inner products: 


1. ( c . 00 = c1 . 0 + c0 . 0 = 0 ) 

   This condition is trivially satisfied for any ( c ). 

  

2. ( c . 11 = c1 . 1 + c0 . 1 = c1 + c0 ) 

Therefore, ( c ) must satisfy the condition ( c1 = c0 ). The possible values for ( c ) are: 

  
( c = 00 ) 

( c = 11 ) 


Thus, the possible values of ( c ) that satisfy the given conditions are ( 00 ) and ( 11 ). 