In [1]:
# transpose conjugate, adjoint

import numpy as np

def transpose(matrix):
    return np.transpose(matrix)

def conjugate_transpose(matrix):
    return np.conj(matrix.T)

def adjoint(matrix):
    return conjugate_transpose(matrix)

# Example usage:
matrix = np.array([[1, 2+3j, 3], [4j, 5, 6]])
print("Original Matrix:")
print(matrix)

print("\nTranspose:")
print(transpose(matrix))

print("\nConjugate Transpose (Hermitian Transpose):")
print(conjugate_transpose(matrix))

print("\nAdjoint:")
print(adjoint(matrix))


Original Matrix:
[[1.+0.j 2.+3.j 3.+0.j]
 [0.+4.j 5.+0.j 6.+0.j]]

Transpose:
[[1.+0.j 0.+4.j]
 [2.+3.j 5.+0.j]
 [3.+0.j 6.+0.j]]

Conjugate Transpose (Hermitian Transpose):
[[1.-0.j 0.-4.j]
 [2.-3.j 5.-0.j]
 [3.-0.j 6.-0.j]]

Adjoint:
[[1.-0.j 0.-4.j]
 [2.-3.j 5.-0.j]
 [3.-0.j 6.-0.j]]


In [2]:
# matrix multiplication

import numpy as np

def matrix_multiplication(matrix1, matrix2):
    return np.dot(matrix1, matrix2)

# Example matrices
matrix_A = np.array([[1, 2, 3],
                     [4, 5, 6]])

matrix_B = np.array([[7, 8],
                     [9, 10],
                     [11, 12]])

# Perform matrix multiplication
result = matrix_multiplication(matrix_A, matrix_B)

print("Matrix A:")
print(matrix_A)

print("\nMatrix B:")
print(matrix_B)

print("\nResult of matrix multiplication (A * B):")
print(result)


Matrix A:
[[1 2 3]
 [4 5 6]]

Matrix B:
[[ 7  8]
 [ 9 10]
 [11 12]]

Result of matrix multiplication (A * B):
[[ 58  64]
 [139 154]]


In [3]:
import numpy as np

def matrix_multiplication(matrix1, matrix2):
    return np.dot(matrix1, matrix2)

# Example matrices with complex entries
matrix_A = np.array([[1+2j, 2+3j],
                     [3+4j, 4+5j]])

matrix_B = np.array([[5+6j, 6+7j],
                     [7+8j, 8+9j]])

# Perform matrix multiplication
result = matrix_multiplication(matrix_A, matrix_B)

print("Matrix A:")
print(matrix_A)

print("\nMatrix B:")
print(matrix_B)

print("\nResult of matrix multiplication (A * B):")
print(result)


Matrix A:
[[1.+2.j 2.+3.j]
 [3.+4.j 4.+5.j]]

Matrix B:
[[5.+6.j 6.+7.j]
 [7.+8.j 8.+9.j]]

Result of matrix multiplication (A * B):
[[-17. +53.j -19. +61.j]
 [-21.+105.j -23.+121.j]]


In [4]:
import numpy as np

# Define matrices A and B
A = np.array([[1+2j, 3-1j],
              [2+1j, 4-2j]])

B = np.array([[3-1j, 2+2j],
              [1-2j, 2-1j]])

# Calculate AB and BA
AB = np.dot(A, B)
BA = np.dot(B, A)

# Check if AB is equal to BA
equal_matrices = np.allclose(AB, BA)

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nAB:")
print(AB)

print("\nBA:")
print(BA)

if equal_matrices:
    print("\nAB and BA are equal.")
else:
    print("\nAB and BA are not equal.")


Matrix A:
[[1.+2.j 3.-1.j]
 [2.+1.j 4.-2.j]]

Matrix B:
[[3.-1.j 2.+2.j]
 [1.-2.j 2.-1.j]]

AB:
[[6.-2.j 3.+1.j]
 [7.-9.j 8.-2.j]]

BA:
[[ 7.+11.j 20. -2.j]
 [10. +0.j  7.-15.j]]

AB and BA are not equal.


In [5]:
import numpy as np

# Define a square matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Calculate the trace of the matrix
trace = np.trace(matrix)

print("Matrix:")
print(matrix)

print("\nTrace of the matrix:", trace)


Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Trace of the matrix: 15


In [6]:
import numpy as np

# Define a complex square matrix
complex_matrix = np.array([[1+2j, 3-1j, 2],
                           [4j, 5, 6+1j],
                           [7-3j, 8, 9]])

# Calculate the trace of the complex matrix
trace_complex = np.trace(complex_matrix)

print("Complex Matrix:")
print(complex_matrix)

print("\nTrace of the complex matrix:", trace_complex)


Complex Matrix:
[[1.+2.j 3.-1.j 2.+0.j]
 [0.+4.j 5.+0.j 6.+1.j]
 [7.-3.j 8.+0.j 9.+0.j]]

Trace of the complex matrix: (15+2j)


In [7]:
import numpy as np

def euclidean_distance(vector1, vector2):
    return np.linalg.norm(vector1 - vector2)

# Example vectors
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

# Calculate the Euclidean distance between the vectors
distance = euclidean_distance(vector_a, vector_b)

print("Vector a:", vector_a)
print("Vector b:", vector_b)
print("\nEuclidean distance between the vectors:", distance)


Vector a: [1 2 3]
Vector b: [4 5 6]

Euclidean distance between the vectors: 5.196152422706632


In [8]:
import numpy as np

def euclidean_distance(vector1, vector2):
    return np.linalg.norm(vector1 - vector2)

# Example complex vectors
vector_a = np.array([1+2j, 3-1j, 2])
vector_b = np.array([4j, 5, 6+1j])

# Calculate the Euclidean distance between the complex vectors
distance = euclidean_distance(vector_a, vector_b)

print("Complex Vector a:", vector_a)
print("Complex Vector b:", vector_b)
print("\nEuclidean distance between the complex vectors:", distance)


Complex Vector a: [1.+2.j 3.-1.j 2.+0.j]
Complex Vector b: [0.+4.j 5.+0.j 6.+1.j]

Euclidean distance between the complex vectors: 5.196152422706632


In [9]:
import numpy as np

def are_orthogonal(vector1, vector2):
    dot_product = np.dot(vector1, vector2)
    return np.isclose(dot_product, 0)

# Example vectors
vector_a = np.array([1, 0, 0])
vector_b = np.array([0, 1, 0])

# Check if the vectors are orthogonal
orthogonal = are_orthogonal(vector_a, vector_b)

print("Vector a:", vector_a)
print("Vector b:", vector_b)

if orthogonal:
    print("\nThe vectors are orthogonal.")
else:
    print("\nThe vectors are not orthogonal.")


Vector a: [1 0 0]
Vector b: [0 1 0]

The vectors are orthogonal.


In [10]:
import numpy as np

def are_orthogonal(vector1, vector2):
    dot_product = np.vdot(vector1, vector2)
    return np.isclose(dot_product, 0)

# Example complex vectors
vector_a = np.array([1+2j, 0-1j, 2])
vector_b = np.array([0+1j, 1, 0+2j])

# Check if the complex vectors are orthogonal
orthogonal = are_orthogonal(vector_a, vector_b)

print("Complex Vector a:", vector_a)
print("Complex Vector b:", vector_b)

if orthogonal:
    print("\nThe complex vectors are orthogonal.")
else:
    print("\nThe complex vectors are not orthogonal.")


Complex Vector a: [1.+2.j 0.-1.j 2.+0.j]
Complex Vector b: [0.+1.j 1.+0.j 0.+2.j]

The complex vectors are not orthogonal.


In [11]:
import numpy as np

def is_hermitian(matrix):
    return np.allclose(matrix, np.conj(matrix.T))

# Example matrix
matrix_A = np.array([[1, 2+3j, 4],
                     [2-3j, 5, 6],
                     [4, 6, 7]])

# Check if the matrix is Hermitian
if is_hermitian(matrix_A):
    print("The matrix is Hermitian.")
else:
    print("The matrix is not Hermitian.")



The matrix is Hermitian.


In [12]:
import numpy as np

def is_unitary(matrix):
    product = np.dot(matrix, np.conj(matrix.T))
    identity = np.eye(matrix.shape[0])
    return np.allclose(product, identity)

# Example unitary matrix
unitary_matrix = 1/np.sqrt(2) * np.array([[1, 1],
                                          [1, -1]])

# Check if the matrix is unitary
if is_unitary(unitary_matrix):
    print("The matrix is unitary.")
else:
    print("The matrix is not unitary.")


The matrix is unitary.


In [13]:
import numpy as np

# Define matrices A and B
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Compute the tensor product of A and B
tensor_product = np.kron(A, B)

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nTensor product of A and B:")
print(tensor_product)


Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Tensor product of A and B:
[[ 5  6 10 12]
 [ 7  8 14 16]
 [15 18 20 24]
 [21 24 28 32]]
